apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-vmoptions
  namespace: nexus
data:
  nexus.vmoptions: |
    -Xms4g
    -Xmx4g
    -XX:MaxDirectMemorySize=6g
    -XX:+UnlockExperimentalVMOptions
    -XX:+UseCGroupMemoryLimitForHeap
    -Djava.util.prefs.userRoot=/nexus-data/javaprefs

