apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-vmoptions
  namespace: nexus
data:
  nexus.vmoptions: |
    -Xms2g
    -Xmx2g
    -XX:MaxDirectMemorySize=3g
    -XX:+UnlockExperimentalVMOptions
    -XX:+UseCGroupMemoryLimitForHeap
    -Djava.util.prefs.userRoot=/nexus-data/javaprefs

