---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-vmoptions
  namespace: newnexus
data:
  nexus.vmoptions: |
    -Xms4g
    -Xmx2g
    -XX:MaxDirectMemorySize=6g
    -XX:+UnlockExperimentalVMOptions
    -XX:+UseCGroupMemoryLimitForHeap
    -Djava.util.prefs.userRoot=/nexus-data/javaprefs
